scale: 0
chucksPerRun: 4
runPerTicks: 5
fastTicks: 20
canSeeOthers: true
colors:
    STONE: 46
    GRASS: 6
    DIRT: 42
    COBBLESTONE: 46
    WOOD: 54
    BEDROCK: 46
    SAND: 10
    GRAVEL: 10
    GOLD_ORE: 46
    IRON_ORE: 46
    COAL_ORE: 46
    LOG: 54
    LEAVES: 14
    SPONGE: 46
    GLASS: 46
    LAPIS_ORE: 46
    LAPIS_BLOCK: 46
    DISPENSER: 54
    SANDSTONE: 14
    NOTE_BLOCK: 26
    AIR: 26
    PISTON_STICKY_BASE: 46
    PISTON_BASE: 46
    AIR: 54
    WOOL: 46
    PISTON_MOVING_PIECE: 46
    GOLD_BLOCK: 5
    IRON_BLOCK: 46
    DOUBLE_STEP: 26
    STEP: 54
    BRICK: 46
    TNT: 46
    BOOKSHELF: 46
    MOSSY_COBBLESTONE: 46
    OBSIDIAN: 34
    MOB_SPAWNER: 38
    WOOD_STAIRS: 54
    CHEST: 30
    DIAMOND_ORE: 46
    DIAMOND_BLOCK: 10
    WORKBENCH: 30
    SOIL: 54
    FURNACE: 38
    BURNING_FURNACE: 46
    SIGN_POST: 54
    AIR: 54
    COBBLESTONE_STAIRS: 30
    AIR: 6
    STONE_PLATE: 46
    AIR: 5
    WOOD_PLATE: 46
    REDSTONE_ORE: 5
    GLOWING_REDSTONE_ORE: 5
    ICE: 54
    SNOW_BLOCK: 46
    AIR: 26
    CLAY: 26
    JUKEBOX: 46
    FENCE: 46
    PUMPKIN: 46
    NETHERRACK: 5
    SOUL_SAND: 5
    GLOWSTONE: 5
    JACK_O_LANTERN: 5
    CAKE_BLOCK: 5
    LOCKED_CHEST: 5
    AIR: 5
    MONSTER_EGGS: 5
    SMOOTH_BRICK: 5
    HUGE_MUSHROOM_1: 5
    HUGE_MUSHROOM_2: 5
    IRON_FENCE: 5
    THIN_GLASS: 5
    MELON_BLOCK: 5
    FENCE_GATE: 5
    BRICK_STAIRS: 5
    SMOOTH_STAIRS: 5
    MYCEL: 5
    NETHER_BRICK: 5
    NETHER_FENCE: 5
    NETHER_BRICK_STAIRS: 5
    ENCHANTMENT_TABLE: 5
    BREWING_STAND: 5
    CAULDRON: 5
    ENDER_PORTAL_FRAME: 5
    ENDER_STONE: 5
    DRAGON_EGG: 5
    REDSTONE_LAMP_OFF: 5
    REDSTONE_LAMP_ON: 5
    WOOD_DOUBLE_STEP: 5
    WOOD_STEP: 5
    SANDSTONE_STAIRS: 5
    EMERALD_ORE: 5
    ENDER_CHEST: 5
    EMERALD_BLOCK: 5
    SPRUCE_WOOD_STAIRS: 5
    BIRCH_WOOD_STAIRS: 5
    JUNGLE_WOOD_STAIRS: 5
    COMMAND: 5
    BEACON: 5
    COBBLE_WALL: 5
    ANVIL: 5
    TRAPPED_CHEST: 5
    GOLD_PLATE: 5
    IRON_PLATE: 5
    DAYLIGHT_DETECTOR: 5
    REDSTONE_BLOCK: 5
    QUARTZ_ORE: 5
    HOPPER: 5
    QUARTZ_BLOCK: 5
    QUARTZ_STAIRS: 5
    DROPPER: 5